$JOB BUILD FORTH SYSTEM
.DELETE *.MP,*.LS,*.RB
.DEL SYS:FORTH.SV
.MAC FORTH,FORTH<FORTH/Q/S/X=120
.MAC FILEIO,FILEIO<FILEIO/Q/S/X=120
.MAC FPARSE,FPARSE<FPARSE/Q/X/S=120
.MAC FHIO,FHIO<FHIO/Q/X/S=120
.MAC INPUT<INPUT/Q/X
.LINK FORTH<FORTH,FILEIO,FPARSE,INPUT,FHIO/K=3/Y/B
.LINK SYS:FORTH,FORTH<FORTH,FILEIO,FPARSE,INPUT,FHIO/K=3/Y
.MAP FORTH.BM<FORTH
.COPY LPT:<FORTH.MP,*.LS
$END
