$JOB BUILD FORTH SYSTEM
.DELETE *.MP,*.LS,*.RB
.DEL SYS:FORTH.SV
.MAC FORTH,FORTH<FORTH/Q/S/X=120
.MAC FTHIO,FTHIO<FTHIO/Q/X/S=120
.MAC INPUT,INPUT<INPUT/Q/X

/ CREATE SYS:FORTH.SV AND LINKER MAP.
.LINK SYS:FORTH,FORTH<FORTH,INPUT,FTHIO/K=3/Y

/ MAKE BINARY FILE FOR MEMORY USAGE MAP.
.LINK FORTH<FORTH,INPUT,FTHIO/K=3/Y/B
.MAP FORTH.BM<FORTH

/ COPY TO HOST SYSTEM FILE
.COPY LPT:<FORTH.MP,*.LS
$END
