$JOB BUILD FORTH SYSTEM
.DELETE *.MP,*.LS,*.RB
.DEL SYS:FORTH.SV
.MAC FORTH,FORTH<FORTH/Q/S/X=120
.MAC FILEIO,FILEIO<FILEIO/Q/S/X=120
.MAC FPARSE,FPARSE<FPARSE/Q/X/S=120
.MAC FHIO,FHIO<FHIO/Q/X/S=120
.MAC INPUT<INPUT/Q/X
/ Create SYS:FORTH.SV and linker map.
.LINK SYS:FORTH,FORTH<FORTH,FILEIO,FPARSE,INPUT,FHIO/K=3/Y
/ Make binary file for memory usage map.
.LINK FORTH<FORTH,FILEIO,FPARSE,INPUT,FHIO/K=3/Y/B
.MAP FORTH.BM<FORTH
/ Copy to host system file
.COPY LPT:<FORTH.MP,*.LS
$END
